version: "3.3"
services:
  time_server:
    build: ./ChronyServer
    volumes:
      - /dev:/dev
      - shared_var:/var/run
    cap_add: 
      - SYS_TIME
    network_mode: host
  gps_server:
    build: ./GPSServer
    volumes:
      - /dev:/dev
      - shared_var:/var/run
    privileged: true
    ports:
      - 2947:2947
    tty: true
    depends_on: 
      - "time_server"

volumes:
  shared_var: