version: "3.3"
services:
  time_server:
    build: ./ChronyServer
    volumes:
      - /dev:/dev
      - shared_var:/var/run
    cap_add: 
      - SYS_TIME
    network_mode: host
  gps_server:
    build: ./GPSServer
    volumes:
      - /dev:/dev
      - shared_var:/var/run
    privileged: true
    ports:
      - 2947:2947
    tty: true
    depends_on: 
      - "time_server"
    network_mode: host
  ntrip_server:
    build: ./NTRIPServer
    ports:
      - 2101:2101
      - 2102:2102
    tty: true

volumes:
  shared_var: