---
- name: Copy the gpsd, chronyd and gps_control containers definitions and code to the raspberry pi and build.
  hosts: all

  tasks:
  - name: Copy over the appropriate container definitions and files.
    ansible.posix.synchronize:
      src: /tmp/ansible/project_files/
      dest: /home/pi/project_files
      rsync_opts:
        - "--no-motd"
        - "--exclude=.git*"
        - "--exclude=ansible_environment"
        - "--exclude=arduino_firmware"
        - "--exclude=docs"
        - "--exclude=LORAArduinoCode"
        - "--exclude=*.md"
        - "--exclude=LICENSE"
        - "--exclude=gps_control/target"
        - "--exclude=GPSServer"
        - "--exclude=ChronyServer"

  #- name: Build the docker containers
  #  community.docker.docker_compose:
  #    project_src: /home/pi/project_files
