---
- name: Install general software
  hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install packages with apt
      apt:
        pkg:
        - vim
        - rsync
        - gpsd-clients
        - python3
        - git
        - build-essential
        - scons

    - name: Setup the hostname
      command: echo {{ ansible_hostname }} > /etc/hostname

    - name: Install rust toolchain.


