---
- name: Setup the the device as a base station
  hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"
    
    - name: Install the needed tools
      apt:
        - vsftp

    - name: Copy over the vsftp configuration file
      ansible.builtin.template:
        src: ../templates/vsftpd.conf
        dest: /etc/vsftpd.conf
        user: root
        groups: root
        mode: '0644'

    - name: Setup the data directory. 
      command: |
        mkdir -f /data
        mkdir -f /data/data
        chmod a-w /data
        chmod 777 /data/data

    - name: Enable the vsftpd service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: vsftpd