---
- name: Setup the the device as a base station
  hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"
    
    - name: Install the needed tools
      apt:
        pkg:
        - vsftpd

    - name: Copy over the vsftp configuration file
      ansible.builtin.copy:
        src: ../templates/vsftpd.conf
        dest: /etc/vsftpd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Setup the data directory. 
      shell: |
        mkdir /data
        mkdir /data/data
        chmod a-w /data
        chmod 777 /data/data

    - name: Enable the vsftpd service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: vsftpd